export type CostCenter =
  | 'ALESSANDRINI'
  | 'PASTORELLI'
  | 'PASSACANTILLI'
  | 'PLENZICH'
  | 'FIRENZE MANUTENZIONI'
  | 'MULTISERVIZI';

export const COST_CENTERS: CostCenter[] = [
  'ALESSANDRINI',
  'PASTORELLI',
  'PASSACANTILLI',
  'PLENZICH',
  'FIRENZE MANUTENZIONI',
  'MULTISERVIZI',
];
