-- Tabella alias attività ACEA/ITALGAS: fonte di verità per la normalizzazione delle attività e la
-- riclassificazione del committente (alias-only; i dati grezzi in `interventi` restano intatti).
-- chiave = normalizzaAttivita(intervento_tipo) [UPPER/NFD-senza-accenti/spazi collassati].
create table if not exists public.acea_attivita_alias (
  id uuid primary key default gen_random_uuid(),
  committente_orig text not null,
  chiave text not null,
  committente_eff text not null,
  macrogruppo text not null,
  attivita_pulita text not null,
  voce smallint,
  attivo boolean not null default true,
  note text,
  created_at timestamptz not null default now(),
  unique (committente_orig, chiave)
);
alter table public.acea_attivita_alias enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='acea_attivita_alias' and policyname='acea_attivita_alias_all_auth') then
    create policy acea_attivita_alias_all_auth on public.acea_attivita_alias for all to authenticated using (true) with check (true);
  end if;
end $$;

insert into public.acea_attivita_alias (committente_orig, chiave, committente_eff, macrogruppo, attivita_pulita, voce, attivo) values
  ('acea','LIMITAZIONE FLUSSO IDRICO','acea','DUNNING','Limitazione flusso idrico',10,true),
  ('acea','LIMITAZIONE MASSIVA','acea','DUNNING','Limitazione massiva',10,true),
  ('acea','LIMITAZIONE MASSIVA SU IMPIANTO','acea','DUNNING','Limitazione massiva',10,true),
  ('acea','LIMITAZIONE MASSIVE','acea','DUNNING','Limitazione massiva',10,true),
  ('acea','LIMITAZIONI MASSICE','acea','DUNNING','Limitazione massiva',10,true),
  ('acea','LIMITAZIONI MASSIVA','acea','DUNNING','Limitazione massiva',10,true),
  ('acea','LIMITAZIONI MASSIVE','acea','DUNNING','Limitazione massiva',10,true),
  ('acea','REGOLARIZZAZIONE FLUSSO IDRICO','acea','DUNNING','Regolarizzazione flusso idrico',null,true),
  ('acea','REVOCA DISATTIVAZIONE CESSATA MOROSITA','acea','DUNNING','Revoca disattivazione',null,true),
  ('acea','REVOCA LIMITAZIONE FLUSSO','acea','DUNNING','Revoca limitazione flusso',null,true),
  ('acea','RIAPERTURA FORNITURA CESSATA MOROSITA','acea','DUNNING','Riapertura fornitura',null,true),
  ('acea','RIATTIVAZIONE FORNITURA','acea','DUNNING','Riattivazione fornitura',null,true),
  ('acea','RIMOZIONE IMPIANTO ABUSIVO','acea','DUNNING','Rimozione impianto abusivo',6,true),
  ('acea','RIM MIS/MOD RADIO PER MOROSITA','acea','DUNNING','Rimozione misuratore per morosità',12,true),
  ('acea','RIMOZIONE MISURATORE PER MOROSITA','acea','DUNNING','Rimozione misuratore per morosità',12,true),
  ('acea','RIPRISTINO DA MOROSITA','acea','DUNNING','Ripristino da morosità',null,true),
  ('lim_massive','LIMITAZIONE MASSIVA','acea','LIMITAZIONI MASSIVE','Limitazione massiva',10,true),
  ('lim_massive','LIMITAZIONI MASSIVE','acea','LIMITAZIONI MASSIVE','Limitazione massiva',10,true),
  ('acea','DUNNING','acea','Scartare','DUNNING',null,false),
  ('acea','DIS00N - DISATTIVAZIONE SUCCESSIVO PASSAGGIO','italgas','Attività alla clientela','Disattivazione passaggio successivo',null,true),
  ('acea','DIS001 - DISATTIVAZIONE PRIMO PASSAGGIO','italgas','Attività alla clientela','Disattivazione primo passaggio',null,true),
  ('acea','S-AI-009','italgas','Attività alla clientela','S-AI-009',null,true),
  ('acea','S-AI-022','italgas','Attività alla clientela','S-AI-022',null,true),
  ('acea','S-AI-022 - SOST PROG CONT ATTIVO < G6 PER TELELETTURA','italgas','Attività alla clientela','S-AI-022',null,true),
  ('acea','S-AI-022 - SOST PROG CONT ATTIVO < G6 PER TELELETTURA GN B','italgas','Attività alla clientela','S-AI-022',null,true),
  ('acea','S-AI-022 - SOST PROG CONT ATTIVO < G6 PER TELELETTURA GN C','italgas','Attività alla clientela','S-AI-022',null,true),
  ('acea','S-AI-049 - VERIFICA MISURATORE IN CAMPO','italgas','Attività alla clientela','S-AI-049',null,true),
  ('acea','S-AI-050 - CAMBIO FORZATO','italgas','Attività alla clientela','S-AI-050',null,true),
  ('acea','S-MR-002','italgas','Attività alla clientela','S-MR-002',null,true),
  ('acea','S-MR-002 - RIATTIVAZ. SERVIZIO SOSPESO PER MOROSITA''','italgas','Attività alla clientela','S-MR-002',null,true),
  ('acea','S-MR-002 A','italgas','Attività alla clientela','S-MR-002 A',null,true),
  ('acea','S-MR-002 A SONDA','italgas','Attività alla clientela','S-MR-002 A',null,true),
  ('acea','S-MR-002 B','italgas','Attività alla clientela','S-MR-002 B',null,true),
  ('acea','S-MR-002 C','italgas','Attività alla clientela','S-MR-002 C',null,true),
  ('acea','S-MR-003 A','italgas','Attività alla clientela','S-MR-003 A',null,true),
  ('acea','S-MR-003 A SONDA','italgas','Attività alla clientela','S-MR-003 A',null,true),
  ('acea','S-PR-001','italgas','Attività alla clientela','S-PR-001',null,true),
  ('acea','S-PR-001 A','italgas','Attività alla clientela','S-PR-001 A',null,true),
  ('acea','S-PR-003','italgas','Attività alla clientela','S-PR-003',null,true),
  ('acea','S-PR-003 A','italgas','Attività alla clientela','S-PR-003 A',null,true),
  ('acea','S-PR-003 A SONDA','italgas','Attività alla clientela','S-PR-003 A',null,true),
  ('acea','S-PR-003 B','italgas','Attività alla clientela','S-PR-003 B',null,true),
  ('acea','S-PR-004','italgas','Attività alla clientela','S-PR-004',null,true),
  ('acea','S-PR-004 A','italgas','Attività alla clientela','S-PR-004 A',null,true),
  ('acea','S-PR-004 B','italgas','Attività alla clientela','S-PR-004 B',null,true),
  ('acea','S-PR-004 C','italgas','Attività alla clientela','S-PR-004 C',null,true),
  ('acea','S-PR-007','italgas','Attività alla clientela','S-PR-007',null,true),
  ('acea','S-PR-007 A','italgas','Attività alla clientela','S-PR-007 A',null,true),
  ('acea','S-PR-007 B','italgas','Attività alla clientela','S-PR-007 B',null,true),
  ('acea','S-PR-009','italgas','Attività alla clientela','S-PR-009',null,true),
  ('acea','S-PR-009 A','italgas','Attività alla clientela','S-PR-009 A',null,true),
  ('acea','S-PR-009 B','italgas','Attività alla clientela','S-PR-009 B',null,true),
  ('acea','S-PR-009 C','italgas','Attività alla clientela','S-PR-009 C',null,true),
  ('acea','S-PR-019 A','italgas','Attività alla clientela','S-PR-019 A',null,true),
  ('acea','S-PR-019 B','italgas','Attività alla clientela','S-PR-019 B',null,true),
  ('acea','S-PR-022 A','italgas','Attività alla clientela','S-PR-022 A',null,true),
  ('acea','S-PR-053 A','italgas','Attività alla clientela','S-PR-053 A',null,true),
  ('acea','S-PR-077','italgas','Attività alla clientela','S-PR-077',null,true),
  ('acea','S-PR-077 A','italgas','Attività alla clientela','S-PR-077 A',null,true),
  ('acea','SOSPENSIONE FORNITURA','italgas','Attività alla clientela','Sospensione fornitura',11,true),
  ('acea','UT MOROSITA'' PRIMO PASSAGGIO','italgas','Attività alla clientela','UT morosità primo passaggio',null,true),
  ('acea','''UT MOROSITA'' PRIMO PASSAGGIO','italgas','Attività alla clientela','UT morosità primo passaggio',null,true),
  ('acea','UT MOROSITA'' RIPASSO','italgas','Attività alla clientela','UT morosità ripasso',null,true),
  ('acea','BONIFICHE','italgas','Bonifiche','Bonifiche',null,true),
  ('acea','BONIFICHE EXTRA','italgas','Bonifiche extra','Bonifiche extra',null,true),
  ('altro','PRONTO INTERVENTO','italgas','PRONTO INTERVENTO','PRONTO INTERVENTO',null,true),
  ('acea','PICARRO','italgas','Ricerca perdite / Bonifiche speciali','Picarro',null,true),
  ('acea','RESINE','italgas','Ricerca perdite / Bonifiche speciali','Resine',null,true),
  ('acea','WFM LAVORI ATTIVITA LAVORI IMPRESA/COLL','italgas','Scartare','WFM LAVORI Attività lavori Impresa/coll',null,false)
on conflict (committente_orig, chiave) do update set
  committente_eff=excluded.committente_eff, macrogruppo=excluded.macrogruppo,
  attivita_pulita=excluded.attivita_pulita, voce=excluded.voce, attivo=excluded.attivo;
